// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfF2iNjkfJ3zXh9mz_0tM2PcXXPWmNgBE',
    appId: '1:924064989764:web:13fa9cb42a71124d923211',
    messagingSenderId: '924064989764',
    projectId: 'ostad-cdfc2',
    authDomain: 'ostad-cdfc2.firebaseapp.com',
    storageBucket: 'ostad-cdfc2.firebasestorage.app',
    measurementId: 'G-LRB91YRCFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvOvSSen_eNfo8dzlsxLzaN22V7d6IEV0',
    appId: '1:924064989764:android:df64e7fbed08679b923211',
    messagingSenderId: '924064989764',
    projectId: 'ostad-cdfc2',
    storageBucket: 'ostad-cdfc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5lqxRCPtbs8AsSnUS_4Yw5XgwKTZqIkE',
    appId: '1:924064989764:ios:f91371efade8b9bf923211',
    messagingSenderId: '924064989764',
    projectId: 'ostad-cdfc2',
    storageBucket: 'ostad-cdfc2.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5lqxRCPtbs8AsSnUS_4Yw5XgwKTZqIkE',
    appId: '1:924064989764:ios:f91371efade8b9bf923211',
    messagingSenderId: '924064989764',
    projectId: 'ostad-cdfc2',
    storageBucket: 'ostad-cdfc2.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvD2ZOpJwqKbUnCIDWUThcMmNBXXgHAfE',
    appId: '1:924064989764:web:41bceaffa867fdb0923211',
    messagingSenderId: '924064989764',
    projectId: 'ostad-cdfc2',
    authDomain: 'ostad-cdfc2.firebaseapp.com',
    storageBucket: 'ostad-cdfc2.firebasestorage.app',
    measurementId: 'G-1Q8TETGN3V',
  );
}
